const allQuestions = [
    { question: "Wat is de hoofdstad van Frankrijk?", options: ["Londen", "Berlijn", "Parijs", "Madrid"], answer: "Parijs" },
    { question: "Welke planeet staat het dichtst bij de zon?", options: ["Venus", "Mars", "Aarde", "Mercurius"], answer: "Mercurius" },
    { question: "Wie ontdekte de zwaartekracht?", options: ["Newton", "Einstein", "Galileo", "Tesla"], answer: "Newton" },
    { question: "Wat is de grootste oceaan op aarde?", options: ["Atlantische Oceaan", "Indische Oceaan", "Arctische Oceaan", "Grote Oceaan"], answer: "Grote Oceaan" },
    { question: "Uit hoeveel continenten bestaat de wereld?", options: ["5", "6", "7", "8"], answer: "7" },
    { question: "Wat is het chemische symbool voor goud?", options: ["Au", "Ag", "Pb", "Fe"], answer: "Au" },
    { question: "Welk land heeft de meeste tijdzones?", options: ["Rusland", "Verenigde Staten", "Frankrijk", "China"], answer: "Frankrijk" },
    { question: "Welk element heeft het chemische symbool 'O'?", options: ["Zuurstof", "Goud", "IJzer", "Koolstof"], answer: "Zuurstof" },
    { question: "Wie schreef het boek '1984'?", options: ["George Orwell", "J.K. Rowling", "Ernest Hemingway", "F. Scott Fitzgerald"], answer: "George Orwell" },
    { question: "Wat is het kleinste land ter wereld?", options: ["Monaco", "Vaticaanstad", "San Marino", "Liechtenstein"], answer: "Vaticaanstad" },
    { question: "Wat is de hoofdstad van Canada?", options: ["Toronto", "Vancouver", "Ottawa", "Montreal"], answer: "Ottawa" },
    { question: "Welk gas is nodig voor menselijke ademhaling?", options: ["Zuurstof", "Koolstofdioxide", "Waterstof", "Stikstof"], answer: "Zuurstof" },
    { question: "Welke kleur krijg je als je blauw en geel mengt?", options: ["Groen", "Paars", "Oranje", "Bruin"], answer: "Groen" },
    { question: "Hoeveel hoeken heeft een zeshoek?", options: ["4", "5", "6", "7"], answer: "6" },
    { question: "Welke stad staat bekend als 'de stad van de liefde'?", options: ["Rome", "Venetië", "Parijs", "Barcelona"], answer: "Parijs" },
    { question: "Welke planeet wordt ook wel de 'rode planeet' genoemd?", options: ["Venus", "Mars", "Jupiter", "Saturnus"], answer: "Mars" },
    { question: "Wie schilderde de Mona Lisa?", options: ["Van Gogh", "Rembrandt", "Leonardo da Vinci", "Michelangelo"], answer: "Leonardo da Vinci" },
    { question: "Wat is het grootste orgaan in het menselijk lichaam?", options: ["Lever", "Hersenen", "Hart", "Huid"], answer: "Huid" },
    { question: "Welke vogel staat bekend om het brengen van baby's?", options: ["Uil", "Duif", "Ooievaar", "Arend"], answer: "Ooievaar" },
    { question: "Hoeveel spelers heeft een standaard voetbalteam op het veld?", options: ["9", "10", "11", "12"], answer: "11" },
    { question: "Wat is de langste rivier in de wereld?", options: ["Amazone", "Mississippi", "Nijl", "Donau"], answer: "Nijl" },
    { question: "Welke planeet heeft de meeste manen?", options: ["Jupiter", "Saturnus", "Uranus", "Mars"], answer: "Saturnus" },
    { question: "Wat is het nationale dier van Nederland?", options: ["Leeuw", "Olifant", "Bever", "Hert"], answer: "Leeuw" },
    { question: "Welke sport wordt gespeeld bij Wimbledon?", options: ["Voetbal", "Tennis", "Rugby", "Golf"], answer: "Tennis" },
    { question: "Wat is de hoofdstad van Australië?", options: ["Sydney", "Melbourne", "Canberra", "Brisbane"], answer: "Canberra" },
    { question: "Wat is het koudste continent op aarde?", options: ["Antarctica", "Europa", "Noord-Amerika", "Azië"], answer: "Antarctica" },
    { question: "Welk metaal is vloeibaar bij kamertemperatuur?", options: ["Kwik", "Ijzer", "Goud", "Zilver"], answer: "Kwik" },
    { question: "Wat is het grootste land ter wereld?", options: ["Canada", "China", "Verenigde Staten", "Rusland"], answer: "Rusland" },
    { question: "Wat is de naam van het paard van Sinterklaas?", options: ["Amerigo", "Storm", "Bliksem", "Vos"], answer: "Amerigo" },
    { question: "Welke noot wordt gebruikt om marsepein te maken?", options: ["Walnoot", "Amandel", "Hazelnoot", "Pinda"], answer: "Amandel" },
    { question: "Welke munt wordt gebruikt in Japan?", options: ["Yuan", "Yen", "Won", "Dollar"], answer: "Yen" },
    { question: "Hoeveel ogen heeft een dobbelsteen?", options: ["18", "20", "21", "22"], answer: "21" },
    { question: "Welke kleur heeft de binnenkant van een kiwi?", options: ["Geel", "Groen", "Oranje", "Rood"], answer: "Groen" },
    { question: "Wat is de snelste landdier?", options: ["Leeuw", "Jachtluipaard", "Tijger", "Wolf"], answer: "Jachtluipaard" },
    { question: "Wie componeerde de Negende Symfonie?", options: ["Bach", "Beethoven", "Mozart", "Chopin"], answer: "Beethoven" },
    { question: "Welke stad is de hoofdstad van Italië?", options: ["Rome", "Milaan", "Napels", "Turijn"], answer: "Rome" },
    { question: "Welk land staat bekend om tulpen en molens?", options: ["Frankrijk", "Nederland", "Duitsland", "België"], answer: "Nederland" },
    { question: "Welke gas is het meest aanwezig in de atmosfeer?", options: ["Zuurstof", "Koolstofdioxide", "Waterstof", "Stikstof"], answer: "Stikstof" }
];
